---
- name: "Apache installation using docker"
  hosts: prod
  pre_tasks:
  - name: "Install docker python"
    pip: name=docker-py
  tasks:
  - name: "Launch docker container"
    docker_container:
      name: "webapp"
      image: "httpd"
      state: started
      ports:
        - "8080:80"
