---
- name: "Apache installation using docker"
  hosts: prod
  become: yes
  vars_files:
    - files/secrets/credentials.yml
  pre_tasks:
  - name: "Install docker python"
    pip: name=docker-py
  - name: "Install some package"
    apt:
      name: "{{ item }}"
      update_cache: yes
    loop:
      - git
      - wget
    when: ansible_facts['os_family'] == "Debian"
  tasks:
  - name: "Copy website file template"
    template: 
      src: index.html.j2
      dest: /home/cedric/index.html
  - name: "Launch docker container"
    docker_container:
      name: "webapp"
      image: "httpd"
      state: started
      ports:
        - "8090:80"
      volumes:
        - /home/cedric/index.html:/usr/local/apache2/htdocs/index.html
